config/routes.rb
require_relative '../app/api/api/v1/collab.rb'
Rails.application.routes.draw do
  resources :devices
  resources :notes
  resources :api_keys
  resources :tags
  resources :activity_transactions
  resources :account_dashboards
  resources :activities
  get 'home/index'

  devise_for :accounts

  root 'home#index'
  mount API::V1::Collab => '/'

end

app/models/note.rb
class Note < ActiveRecord::Base
	acts_as_paranoid
	#association 
	has_one :activity_transaction
	has_one :account_dashboard
	belongs_to :account
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:descriptin, :deleted_at)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.haml
= form_for @note do |f|
  - if @note.errors.any?
    #error_explanation
      %h2= "#{pluralize(@note.errors.count, "error")} prohibited this note from being saved:"
      %ul
        - @note.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :descriptin
    = f.text_area :descriptin
  .field
    = f.label :deleted_at
    = f.datetime_select :deleted_at
  .actions
    = f.submit 'Save'

app/views/notes/edit.html.haml
%h1 Editing note

= render 'form'

= link_to 'Show', @note
\|
= link_to 'Back', notes_path

app/views/notes/index.html.haml
%h1 Listing notes

%table
  %thead
    %tr
      %th Descriptin
      %th Deleted at
      %th
      %th
      %th

  %tbody
    - @notes.each do |note|
      %tr
        %td= note.descriptin
        %td= note.deleted_at
        %td= link_to 'Show', note
        %td= link_to 'Edit', edit_note_path(note)
        %td= link_to 'Destroy', note, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Note', new_note_path

app/views/notes/new.html.haml
%h1 New note

= render 'form'

= link_to 'Back', notes_path

app/views/notes/show.html.haml
%p#notice= notice

%p
  %b Descriptin:
  = @note.descriptin
%p
  %b Deleted at:
  = @note.deleted_at

= link_to 'Edit', edit_note_path(@note)
\|
= link_to 'Back', notes_path