config/routes.rb
require_relative '../app/api/api/v1/collab.rb'
Rails.application.routes.draw do
  resources :devices
  resources :notes
  resources :api_keys
  resources :tags
  resources :activity_transactions
  resources :account_dashboards
  resources :activities
  get 'home/index'

  devise_for :accounts

  root 'home#index'
  mount API::V1::Collab => '/'

end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
	acts_as_paranoid

    #Callbacks
	before_create :generate_access_token, :set_expires_at

    #Association
  	belongs_to :account   

    #Predefined query
    default_scope { where(active: true) }

    #Validations
    validates :access_token,:expires_at,:account_id, presence: true



  	def generate_access_token
    	begin
    		self.access_token = SecureRandom.hex(40)
    	end while self.class.exists?(access_token: access_token)
  	end

   
  	def expired?
  		DateTime.now >= self.expires_at
  	end

  	def set_expires_at
  		 self.expires_at = DateTime.now+30.days
  	end
   
    def inactive
      self.active = false;
    end
end

app/controllers/api_keys_controller.rb
class ApiKeysController < ApplicationController
  before_action :set_api_key, only: [:show, :edit, :update, :destroy]

  # GET /api_keys
  # GET /api_keys.json
  def index
    @api_keys = ApiKey.all
  end

  # GET /api_keys/1
  # GET /api_keys/1.json
  def show
  end

  # GET /api_keys/new
  def new
    @api_key = ApiKey.new
  end

  # GET /api_keys/1/edit
  def edit
  end

  # POST /api_keys
  # POST /api_keys.json
  def create
    @api_key = ApiKey.new(api_key_params)

    respond_to do |format|
      if @api_key.save
        format.html { redirect_to @api_key, notice: 'Api key was successfully created.' }
        format.json { render :show, status: :created, location: @api_key }
      else
        format.html { render :new }
        format.json { render json: @api_key.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /api_keys/1
  # PATCH/PUT /api_keys/1.json
  def update
    respond_to do |format|
      if @api_key.update(api_key_params)
        format.html { redirect_to @api_key, notice: 'Api key was successfully updated.' }
        format.json { render :show, status: :ok, location: @api_key }
      else
        format.html { render :edit }
        format.json { render json: @api_key.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api_keys/1
  # DELETE /api_keys/1.json
  def destroy
    @api_key.destroy
    respond_to do |format|
      format.html { redirect_to api_keys_url, notice: 'Api key was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_api_key
      @api_key = ApiKey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def api_key_params
      params.require(:api_key).permit(:access_token, :account_id, :state, :expires_at, :deleted_at)
    end
end

app/helpers/api_keys_helper.rb
module ApiKeysHelper
end

app/views/api_keys/_form.html.haml
= form_for @api_key do |f|
  - if @api_key.errors.any?
    #error_explanation
      %h2= "#{pluralize(@api_key.errors.count, "error")} prohibited this api_key from being saved:"
      %ul
        - @api_key.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :access_token
    = f.text_field :access_token
  .field
    = f.label :account_id
    = f.number_field :account_id
  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :expires_at
    = f.datetime_select :expires_at
  .field
    = f.label :deleted_at
    = f.datetime_select :deleted_at
  .actions
    = f.submit 'Save'

app/views/api_keys/edit.html.haml
%h1 Editing api_key

= render 'form'

= link_to 'Show', @api_key
\|
= link_to 'Back', api_keys_path

app/views/api_keys/index.html.haml
%h1 Listing api_keys

%table
  %thead
    %tr
      %th Access token
      %th Account
      %th State
      %th Expires at
      %th Deleted at
      %th
      %th
      %th

  %tbody
    - @api_keys.each do |api_key|
      %tr
        %td= api_key.access_token
        %td= api_key.account_id
        %td= api_key.state
        %td= api_key.expires_at
        %td= api_key.deleted_at
        %td= link_to 'Show', api_key
        %td= link_to 'Edit', edit_api_key_path(api_key)
        %td= link_to 'Destroy', api_key, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Api key', new_api_key_path

app/views/api_keys/new.html.haml
%h1 New api_key

= render 'form'

= link_to 'Back', api_keys_path

app/views/api_keys/show.html.haml
%p#notice= notice

%p
  %b Access token:
  = @api_key.access_token
%p
  %b Account:
  = @api_key.account_id
%p
  %b State:
  = @api_key.state
%p
  %b Expires at:
  = @api_key.expires_at
%p
  %b Deleted at:
  = @api_key.deleted_at

= link_to 'Edit', edit_api_key_path(@api_key)
\|
= link_to 'Back', api_keys_path