config/routes.rb
require_relative '../app/api/api/v1/collab.rb'
Rails.application.routes.draw do
  resources :devices
  resources :notes
  resources :api_keys
  resources :tags
  resources :activity_transactions
  resources :account_dashboards
  resources :activities
  get 'home/index'

  devise_for :accounts

  root 'home#index'
  mount API::V1::Collab => '/'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	acts_as_paranoid

	#association 
	belongs_to :activity_transaction
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:description, :deleted_at)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.haml
= form_for @tag do |f|
  - if @tag.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
      %ul
        - @tag.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :deleted_at
    = f.datetime_select :deleted_at
  .actions
    = f.submit 'Save'

app/views/tags/edit.html.haml
%h1 Editing tag

= render 'form'

= link_to 'Show', @tag
\|
= link_to 'Back', tags_path

app/views/tags/index.html.haml
%h1 Listing tags

%table
  %thead
    %tr
      %th Description
      %th Deleted at
      %th
      %th
      %th

  %tbody
    - @tags.each do |tag|
      %tr
        %td= tag.description
        %td= tag.deleted_at
        %td= link_to 'Show', tag
        %td= link_to 'Edit', edit_tag_path(tag)
        %td= link_to 'Destroy', tag, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tag', new_tag_path

app/views/tags/new.html.haml
%h1 New tag

= render 'form'

= link_to 'Back', tags_path

app/views/tags/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @tag.description
%p
  %b Deleted at:
  = @tag.deleted_at

= link_to 'Edit', edit_tag_path(@tag)
\|
= link_to 'Back', tags_path