config/routes.rb
require_relative '../app/api/api/v1/collab.rb'
Rails.application.routes.draw do
  resources :devices
  resources :notes
  resources :api_keys
  resources :tags
  resources :activity_transactions
  resources :account_dashboards
  resources :activities
  get 'home/index'

  devise_for :accounts

  root 'home#index'
  mount API::V1::Collab => '/'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	acts_as_paranoid

  #association 
  has_many :account_dashborads
  has_many :accounts, through: :account_dashborads
  has_many :activity_transactions
  has_many :images

  #validation
  validates_uniqueness_of :name

  #callback
  before_create :default_options
  

  state_machine :state,:initial => :pending do
    # Events
    event :approve do
      transition :pending => :approved
    end
    event :pending do
      transition :contest => :pending
    end
    event :archieved do
      transition :contest => :archieved
    end

    # Transitions
    before_transition :approved => :pending do |activity|
      activity.approved_at = nil
    end

    before_transition :pending => :approved do |activity|
      activity.touch(:approved_at)
    end

    before_transition any => :unactive do |activity, transition|
      activity.touch(:archived_at)
    end 
  end

  def default_options
    self.state = 'pending'
  end

	def self.input_types
  	{
    		1 => {name: "STAR",data_type: "DECIMAL"},
    		2 => {name: "COMLETE",data_type: "BOOLEAN"}
  	}
	end

  def input_type
    return self.class.input_types[self.input_type_id.to_i]
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|

      puts "X"*200
      puts params[:image]
      if @activity.save
          # (1..4).each do |i|
          #   unless params["image#{i}".to_sym].nil?
              Image.create(name: params[:image],activity_id: @activity.id);
          #   end
          # end
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :description, :deleted_at, :state)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.haml
= form_for @activity , html: {:multipart => true}do |f|
  - if @activity.errors.any?
    #error_explanation
      %h2= "#{pluralize(@activity.errors.count, "error")} prohibited this activity from being saved:"
      %ul
        - @activity.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :deleted_at
    = f.datetime_select :deleted_at
  .field
    = f.label :state
    = f.text_field :state
  .field
    = label_tag :image
    = file_field_tag :image, multiple: true 
  .actions
    = f.submit 'Save'

app/views/activities/edit.html.haml
%h1 Editing activity

= render 'form'

= link_to 'Show', @activity
\|
= link_to 'Back', activities_path

app/views/activities/index.html.haml
%h1 Listing activities

%table
  %thead
    %tr
      %th Name
      %th Description
      %th Deleted at
      %th State
      %th
      %th
      %th

  %tbody
    - @activities.each do |activity|
      %tr
        %td= activity.name
        %td= activity.description
        %td= activity.deleted_at
        %td= activity.state
        %td= link_to 'Show', activity
        %td= link_to 'Edit', edit_activity_path(activity)
        %td= link_to 'Destroy', activity, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Activity', new_activity_path

app/views/activities/new.html.haml
%h1 New activity

= render 'form'

= link_to 'Back', activities_path

app/views/activities/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @activity.name
%p
  %b Description:
  = @activity.description
%p
  %b Deleted at:
  = @activity.deleted_at
%p
  %b State:
  = @activity.state

= link_to 'Edit', edit_activity_path(@activity)
\|
= link_to 'Back', activities_path